/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ykpirxstfagkspgxdvsm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrcGlyeHN0ZmFna3NwZ3hkdnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNjAyNTIsImV4cCI6MjA3NDkzNjI1Mn0.-kxwndtK6eSCiA17Ig6EDralIKP-Q4NFGkDTNYYubsY"